import { SvelteComponent, init, safe_not_equal, create_component, mount_component, noop, transition_in, transition_out, destroy_component } from 'svelte/internal';
import { FRUser } from '@forgerock/javascript-sdk';
import { browser } from '$app/env';
import { goto } from '$app/navigation';
import { email, isAuthenticated, username } from '../global-state.js';
import Loading from '../components/utilities/loading.svelte.js';

/* src/lib/views/logout.svelte generated by Svelte v3.47.0 */

function create_fragment(ctx) {
	let loading;
	let current;

	loading = new Loading({
			props: {
				classes: "pt-5",
				message: "You're being logged out ..."
			}
		});

	return {
		c() {
			create_component(loading.$$.fragment);
		},
		m(target, anchor) {
			mount_component(loading, target, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(loading.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(loading.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(loading, detaching);
		}
	};
}

function instance($$self) {
	(async () => {
		if (browser) {
			await FRUser.logout();
			email.set('');
			isAuthenticated.set(false);
			username.set('');
			goto('/');
		}
	})();

	return [];
}

class Logout extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export { Logout as default };
