import { SvelteComponent, init, safe_not_equal, element, attr, insert, append, noop, detach } from 'svelte/internal';

/* src/lib/components/journey/callbacks/unknown.svelte generated by Svelte v3.47.0 */

function create_fragment(ctx) {
	let div;
	let p;

	return {
		c() {
			div = element("div");
			p = element("p");
			p.textContent = `${`Warning: unknown callback type, ${/*callbackType*/ ctx[0]}, isn't handled`}`;
			attr(div, "class", "form-group");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, p);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { callback } = $$props;
	let callbackType = callback.getType();

	$$self.$$set = $$props => {
		if ('callback' in $$props) $$invalidate(1, callback = $$props.callback);
	};

	return [callbackType, callback];
}

class Unknown extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { callback: 1 });
	}
}

export { Unknown as default };
